config/routes.rb
Rails.application.routes.draw do

  root :to => 'static_pages#home'
  # get 'password_resets/new'
  # get 'password_resets/edit'
  # resources :password_resets,     only: [:new, :create, :edit, :update]

  get 'sessions/new'
  get 'users/new'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  
  resources :submissions
    # get 'submissions/submit'
    post 'submissions/:id', to: 'submissions#status_change'
  

  
  get 'static_pages/home'
  get 'static_pages/awards'
  get 'static_pages/help'
  get 'static_pages/about'
  get 'static_pages/submit'
  get 'static_pages/login'
  get 'static_pages/check_mail'
  get 'static_pages/approved_index', to: 'submissions#approved_index'
  get 'static_pages/approved_month', to: 'submissions#approved_month'
  get 'static_pages/archive', to: 'submissions#archive'
  get 'static_pages/all', to: 'submissions#get_all'

  # get 'events/new', to: 'events#new', as: :events_new_path
  # get 'events/show'
  # get 'events/edit', to: 'events#edit', as: :events_edit_path

   
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :events
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_admin_view.html.erb
<div class="admin-bar">
    <!--DATES AND LINKS-->
    <div class="admin-bar--element">
        <a href="/events/new" class="admin-bar--btn"> <i class="fas fa-link"></i> Home Page Links </a> 
    </div>

    <!--ALL USERS-->
    <div class="admin-bar--element">
      <a href="/users" class="admin-bar--btn"> <i class="fas fa-users"></i> All Users </a> 
    </div>

    <!--NEW SUBMISSIONS-->
    <div class="admin-bar--element">
        <%= link_to "# New Submissions", submissions_path, class: "admin-bar--btn" %>
    </div>
    
    <!--APPROVED SUBMISSION-->
    <div class="admin-bar--element">
       
            <div class="dropdown">
                <button class="admin-bar--btn dropdown-toggle" type="button" data-toggle="dropdown">
                <i class="fas fa-calendar-day"></i> APPROVED MONTH
                  <span class="caret"></span></button>
                  <ul class="dropdown-menu">
                    <li><%= link_to "February 2020", static_pages_approved_month_path(:month => 'February 2020') %></li>
                    <li><%= link_to "March 2020", static_pages_approved_month_path(:month => 'March 2020') %></li>
                    <li><%= link_to "April 2020", static_pages_approved_month_path(:month => 'April 2020') %></li>
                    <li><%= link_to "May 2020", static_pages_approved_month_path(:month => 'May 2020') %></li>
                    <li><%= link_to "June 2020", static_pages_approved_month_path(:month => 'June 2020') %></li>
                    <li><%= link_to "July 2020" , static_pages_approved_month_path(:month => 'July 2020"') %></li>
                    <li><%= link_to "07 April", static_pages_approved_month_path(:month => 'April') %></li>
                    <li><%= link_to "August 2020", static_pages_approved_month_path(:month => 'August 2020') %></li>
                    <li><%= link_to "September 2020", static_pages_approved_month_path(:month => 'September 2020') %></li>
                    <li><%= link_to "November 2020", static_pages_approved_month_path(:month => 'November 2020') %></li>
                    <li><%= link_to "December 2020", static_pages_approved_month_path(:month => 'December 2020') %></li>
                    <li ><%= link_to "January 2021", static_pages_approved_month_path(:month => 'January 2021') %></li>
                    <li><%= link_to "Rejected", static_pages_approved_month_path(:month => 'Rejected') %></li>
                    <li><%= link_to "Archive", static_pages_approved_month_path(:month => 'Archive') %></li>
                  </ul>
            </div> 
    </div>


    <!--All Submissions-->
    <div class="admin-bar--element">
    <%= link_to "@ All Submissions", static_pages_all_path, class: "admin-bar--btn" %>
    </div>
    
</div>
       

    

app/views/shared/_approved_list_out.html.erb
<% if current_user.admin? %>

 
  <% @approval.each do |accept| %>
    <%= render accept %>
  <% end %>

  
<% else %>
  <div class="row text-center">
      <h3>You do not have permission to view this page</h3>
  </div>

<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_home-content.html.erb
<div class="row home--top">
    <section>
        <div class="col-xs-12">
            <span class="home--top-header">A Short Film Competition for Portland's Local Filmmakers</span>
        </div>
        <div class="col-md-1 col-sm-4 col-xs-4">
            <a href="https://curiouscomedy.org/" target="_blank"><img class="logo" src="https://curiouscomedy.org/wp-content/uploads/curious-comedy-theater-logo-2.png" alt="Curious Comedy Theater" ></a>
        </div>
        <div class="col-md-10 col-sm-8 col-xs-8">
            <a href="https://curiouscomedy.org/" target="_blank" class="home--top-cc"> <i class="fas fa-play"></i> A Curious Comedy Event</a>
        </div>
    </section>
</div>

<div class="row ">
    <div class="col-md-8 home--top">
        <div class="col-md-12 video--label">
            Portland's Funniest Video Winner
        </div>
        <div class="col-md-12">
            <div class="flex-video widescreen"> 
                <iframe width="560" height="315" src="https://www.youtube.com/embed/H8YwGdcBArE" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe> 
            </div>
        </div>
        <div class="col-md-12">
            <div class="video--info">
                <strong> PORTLAND’S FUNNIEST VIDEOS </strong> ain’t just another LAUGH ‘TIL YOU WET YOUR PANTS kinda evening.
        No, it’s much more than that. It’s a comedic, short-film competition EVERY DAMN MONTH at Curious Comedy Theater. <br><br>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <section>
            <div class="home--top-dates">

                
                <a href="https://www.facebook.com/events/709152686160358/?active_tab=about" target="_blank" class="home--top-screening"> <i class="far fa-calendar"></i> Next screening : December 18th </a>
                <a href="/submissions/new" class="home--top-deadline"><i class="fas fa-clock"></i> Submit By : December 16th </a>
                <a href="https://tkts.to/e/portland-s-funniest-videos" target="_blank" class="home--top-tickets"><i class="fas fa-ticket-alt"></i> Buy Tickets</a>
            </div>
        </section>
        <div class="row">
            <% if logged_in? %>
                <%= render 'shared/user_info' %>
            <% else %>
                <%= render '/sessions/login_form' %>
            <% end %>
        </div>
    </div>
    
</div>

<div class="row">
    <div class="video--first-place"><i class="fas fa-award"></i> First Place winners</div>

    <% @first.each do |first| %>
        <div class="col-md-4">
            <%= render "shared/player", submission: first %>
        </div>
    <%end%>

</div>
<div class="row">
    <span class="video--award-button"><%= link_to "All 1st Winners", static_pages_awards_path(:category => 'First Place', :place => '1st') %></span>
</div>


<div class=row>
    <div class="video--first-place">Second Place winners</div>
    <% @second.each do |second| %>
        <div class="col-md-4">
            <%= render "shared/player", submission: second %>
        </div>
    <%end%>

</div>
<div class="row">
    <span class="video--award-button"><%= link_to "All 2nd Winners", static_pages_awards_path(:category => 'Second Place', :place => '2nd') %></span>
</div>

<div class="row">
    <div class="video--first-place">Third Place Place winners</div>
    <% @third.each do |third| %>
        <div class="col-md-4">
            <%= render "shared/player", submission: third %>
        </div>
    <%end%>

</div>
<div class="row">
    <span class="video--award-button"><%= link_to "All 3rd Winners", static_pages_awards_path(:category => 'Third Place', :place => '3rd') %></span>

</div>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse">
 <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="https://curiouscomedy.org/" target="_blank">
        <div class='c-brand'> 
          <div class="c-brand-title">
            Curious Comedy Theater
          </div>
        </div>
      </a>
    </div>

     <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
   
      <ul class=" nav navbar-nav navbar-right">
        <li><%= link_to "Home", static_pages_home_path %></li>
        <li><%= link_to "About", static_pages_about_path %></li>
        <li><%= link_to "How To", static_pages_help_path %></li>
        <li><%= link_to "Submit", new_submission_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
          <ul class="dropdown-menu">
    
           
            <% if logged_in? %>
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
               <li role="separator" class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            <% else %>
              <li><%= link_to "Sign up", signup_path %></li>
               <li role="separator" class="divider"></li>
              <li><%= link_to "Login", login_path %></li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse --> 



  </div>
  </div>
</nav>

app/views/shared/_old_nav.html.erb
<!-- Fixed navbar -->
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
        aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Portland's Funniest Video", static_pages_home_path, class: "navbar-brand navbar--pfv-brand" %>
      <!--<a href="https://curiouscomedy.org/" target="_blank"><img class="logo" src="http://curiouscomedy.org/images/logo.png" alt="Curious Comedy Theater" ></a>-->
    </div>

    <div id="navbar" class="navbar-collapse collapse navbar-right">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Home", static_pages_home_path %></li>
        <li><%= link_to "About", static_pages_about_path %></li>
        <li><%= link_to "HowTo", static_pages_help_path %></li>
        <li><%= link_to "Submit", new_submission_path %></li>

        <% if logged_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Account <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Profile", current_user %></li>
            <li><%= link_to "Settings", edit_user_path(current_user) %></li>
            <li class="divider"></li>
            <li>
              <%= link_to "Log out", logout_path, method: :delete %>
            </li>
          </ul>
        </li>
        <% else %>
        <li><%= link_to "Signup", signup_path %></li>
        <% end %>



    </div>
  </div>
  <!--/.nav-collapse -->
</nav>

app/views/shared/_player.html.erb
<div class="top-spacer-sm">

    <div class="player--place">
        <% if submission.winning_month %> <%= submission.winning_month %> <%else %> Status: <%= submission.status %>
        <%end%>
    </div>
    <div class="player--video">
        <div class="flex-video widescreen"><%= get_video_iframe(submission.link) %> </div>
    </div>
</div>

app/views/shared/_please_log_in.html.erb
<div class="well">
    
<div class="row">

        
    <div class="col-md-12 text-center">
        <p>You must be <%= link_to "Signed in", login_path %> to submit a film.</p>
 
    </div>

</div>
</div>

app/views/shared/_standard_greeting.html.erb
<div class="row pad-small">
    <div class="col-md-6">

    <span class="portland">Portland's </br> Funniest Video </span> 
    <p >A Short film competition for Portland's local filmmakers.</p>
    </div>
</div>
<div class="row">
    <div class="col-md-7">    
        <div class="well">
            <!--VIDEO PLAYER-->
           <div class="flex-video widescreen"> 
            <iframe width="560" height="315" src="https://www.youtube.com/embed/OOmIcigpxHE" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
           </div>
        </div>
    </div>
    <div class="col-md-5">
        <div class="well">
            <% if logged_in? %>
                <%= render 'shared/user_info' %>
            <% else %>
                <h2 class="text-center">Log in</h2>
                <%= render '/sessions/login_form' %>
            <% end %>
        </div>
    </div>
    
    <div class="col-md-12">
        <div class="well text-left">
          <p> 
       <strong>   WHAT’S SO DAMN FUNNY, PORTLAND?!? </strong> Well, we’ll tell ya. Your videos, that’s what!<br><br>
       
       <strong> PORTLAND’S FUNNIEST VIDEOS </strong> ain’t just another LAUGH ‘TIL YOU WET YOUR PANTS kinda evening.
        No, it’s much more than that. It’s a comedic, short-film competition EVERY DAMN MONTH at Curious Comedy Theater. <br><br>
        
        Maybe your video will win the Monthly Audience Choice award. Or, you’ll win a gag award <strong> EVERY DAMN MONTH </strong>.
        But one thing’s for sure. You’ll finally get your 15 seconds of fame. And, in March (every March) one of your 
        videos could win the title of Portland’s Funniest Video. <br><br>

         <strong>SO HOW DOES IT WORK? —</strong>
        <br><br>
        First, Portland film nerds accept the challenge to make Portland laugh. Next, they submit their funniest videos — 
        no more than 7 minutes long each. Then, their best creative work duke it out to WIN PRIZES at the event. 

        </div>
    </div>
</div>


   

app/views/shared/_sub_feed.html.erb
      <% if @submissions != nil %>
         <h3>Submissions (<%= @submissions.count %>)</h3>
         <ol class="microposts">
            <%= render @submissions %>
        </ol>
      <%= will_paginate @submissions %>
      <% else %>
          <div class="well text-center">
            <h3> You Have No Submissions Yet </h3>
          </div> 
      <% end %>

app/views/shared/_submissions.html.erb
<% render @submissios %>

app/views/shared/_submit_form.html.erb
<div class="col-md-12 col-md-offset-0 home--login-top home--top">
  <spam class="home--login-top--label text-center"><i class="fas fa-user"></i> Submit Your Film</spam>
</div>

<div class="col-md-12 home--login">
  <%= form_for(@submit) do |f| %>
    <div class="form-group">
    <%= render 'shared/error_messages', object: f.object %>
    <!--TITLE-->
    <div class="row">
      <div class="col-md-12 text-left">
        <%= f.label :title, "Title" %>
      </div>
      <div class="col-md-12">
        <%= f.text_field :title, class: 'form-control', placeholder: "What is the name of your film?" %>  
      </div>
    </div>
    
    <!--RUN TIME-->
    <div class="row">
      <div class="col-xs-2 text-left">
          <%= f.label :length, "Runtime " %>
      </div>
      <div class="col-xs-4">
          <%= f.select :length, ['1','2','3','4','5','6', '7','8','9','10'], class: 'form-control' %>  
      </div>
    </div>
    <!--LINK-->
    <div class="row">
      <div class="col-md-12 text-left">
          <%= f.label :link, "Link" %>
      </div>
      <div class="col-md-12">
          <%= f.text_field :link, class: 'form-control', placeholder: 'Youtube or Vimeo links onlys' %>
      </div>
    </div>
    
    <!--VIMEO PASSWORD-->
    <div class="row">
      <div class="col-md-12 text-left">
          <%= f.label :password, "Password", placeholder: "If vimeo link is password protected" %>
      </div>
      <div class="col-md-12">
          <%= f.text_field :password, class: 'form-control', placeholder: 'If link is password protected.' %>
      </div>
    </div>
    
    <!--DESCRIPTION-->
    <div class="row">
      <div class="col-md-12  text-left">
          <%= f.label :description, "Synopsis" %>
      </div>
      <div class="col-md-12">
          <%= f.text_area :description, class: 'form-control', rows: '4', placeholder: "Tell us about your film in 200 characters." %>
      </div>
    </div>
    <!--PREFERRED MONTH-->
    <div class="row">
      <div class="col-xs-4 text-left">
          <%= f.label :preferred_month, "Preferred Month " %>
      </div>
      <div class="col-md-8">
          <%= f.select :preferred_month, ['Any Month', 'January 2020','February 2020','March 2020','April 2020','May 2020','June 2020', 'July 2020', 'August 2020', 'September 2020', 'October 2020', 'November 2020', 'December 2020'], class: 'form-control' %>  
  
      </div>
    </div>

    <!--REUSE-->
    <div class="row">
      <div class="col-xs-3 col-md-offset-0 text-left">
        <%= f.label :reuse, "Allow replays", class: "form-check-label text-right" %>
      </div>
      <div class="col-xs-1">
        <%= f.check_box :reuse, {:checked=> "checked"}%> 
      </div>
      <div class="col-xs-8">
        Can the theater replay this film at other events.
      </div>
    </div> 
        <br></br>
    <!--HAS RIGHTS-->
    <div class="row">
      <div class="col-xs-3 text-left">
        <%= f.label :has_rights, "All Rights", class: "form-check-label text-right" %>
      </div>
      <div class="col-xs-1">
        <%= f.check_box :has_rights %> 
      </div>
      <div class="col-xs-8">
        You have the all rights to play this video.
      </div>
          
    </div> 
        <br></br>
    <div class="row">
      <div class="col-md-4 col-md-offset-4 top-bump">
          <%= f.submit "Submit", class: "btn btn-primary btn-lg btn-block" %>
      </div>
      
    </div>
  
    </div>
  <% end %>
</div>

app/views/shared/_user_info.html.erb
    <div class="col-xs-12  home--login">
        <%= link_to gravatar_for(current_user, size: 50), current_user %>
        <h3>
            <%= link_to current_user.name, current_user %>
        </h3>  
         <%= link_to "Submission A Film", new_submission_path, class: "video--award-button" %> 
    </div>