config/routes.rb
Rails.application.routes.draw do

  root :to => 'static_pages#home'
  # get 'password_resets/new'
  # get 'password_resets/edit'
  # resources :password_resets,     only: [:new, :create, :edit, :update]

  get 'sessions/new'
  get 'users/new'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  
  resources :submissions
    # get 'submissions/submit'
    post 'submissions/:id', to: 'submissions#status_change'
  

  
  get 'static_pages/home'
  get 'static_pages/awards'
  get 'static_pages/help'
  get 'static_pages/about'
  get 'static_pages/submit'
  get 'static_pages/login'
  get 'static_pages/check_mail'
  get 'static_pages/approved_index', to: 'submissions#approved_index'
  get 'static_pages/approved_month', to: 'submissions#approved_month'
  get 'static_pages/archive', to: 'submissions#archive'
  get 'static_pages/all', to: 'submissions#get_all'

  # get 'events/new', to: 'events#new', as: :events_new_path
  # get 'events/show'
  # get 'events/edit', to: 'events#edit', as: :events_edit_path

   
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :events
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/submission.rb
class Submission < ApplicationRecord
    belongs_to :user
    default_scope -> { order(created_at: :desc) }
    validates :user_id, presence: true
    validates :title, presence: true, length: { maximum: 50 }
    validates :length, presence: true
    validates :link, presence: true, length: { maximum: 200 }
    validates :description, presence: true, length: { maximum: 250 }
    validates :has_rights, :acceptance => true
    
    def send_new_submission_email
        UserMailer.submission_notification(self).deliver_now
    end

end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
    before_action :require_login
    before_action :logged_in_user, only: [:create, :destroy]
    include VideosHelper
    
    def index
        @submissions = Submission.where(status: 'Being Reviewed').paginate(page: params[:page], :per_page => 8) 
    end
    
    def new
        @submit = Submission.new
    end
    
    def create
        @submit = current_user.submissions.build(submit_params)
        # @submit = current_user.Submission.build(submit_params)
        if @submit.save
            @submit.send_new_submission_email
            flash[:success] = "Your Video has been submitted"
            redirect_to current_user
        else
            render 'new'
        end
    end
    
    def show
        @submission = Submission.find(params[:id])
        @user = User.find(@submission.user_id)
    end
    
    def edit
        @submission = Submission.find(params[:id])
    end
    
    def update
        @submission = Submission.find(params[:id])
        if @submission.update_attributes(submit_params)
            flash[:success] = "Submission Details were updated"
            redirect_to @submission
        else
            render 'edit'
        end
    end
    
    def get_all 
        @submissions = Submission.all.paginate(page: params[:page])
    end
    
    def approved_index
        @approval = Submission.where(approved: true).paginate(page: params[:page], :per_page => 8) 
        @runtime = @approval.sum {|h| h[:length].to_i }
    end
    
    def approved_month
        @month = params[:month]
        @approval = Submission.where(status: @month)
        @runtime = @approval.sum {|h| h[:length].to_i }
    end
    
    def archive
        @approval = Submission.where(status: 'Archive').paginate(page: params[:page], :per_page => 8) 
        @runtime = @approval.sum {|h| h[:length].to_i }
    end
    
    def destroy
        Submission.find(params[:id]).destroy
        flash[:success] = "submission deleted"
        redirect_to submissions_url
    end
    
    def status_change
        status = params[:status]
        @approve = Submission.find(params[:id])

        if status == 'archive'
            @approve.status = 'Archive'
            @approve.approved = true
        
            if @approve.save
                flash[:success] = "#{@approve.title} has been send to the archive"
                redirect_to @approve
            else
                flash[:error] = @approve.errors.full_messages
                redirect_to @approve
            end
        elsif status == 'reject'
            @approve.status = 'Rejected'
            @approve.approved = false
       
            if @approve.save
                flash[:success] = "#{@approve.title} has been rejected"
                redirect_to @approve
            else
                flash[:error] = @approve.errors.full_messages
                redirect_to @approve
            end
        elsif status == "review" 
            @approve.status = "Being Reviewed"
            @approve.approved = false
            
            if @approve.save
                flash[:success] = "#{@approve.title} has been set to being Reviewed"
                redirect_to @approve
            else
                flash[:error] = @approve.errors.full_messages
                redirect_to @approve
            end
        else 
            @approve.status = status
            @approve.approved = true
            
            if @approve.save
                flash[:success] = "#{@approve.title} has been added to #{status}"
                redirect_to @submit = Submission.new
            else
                flash[:error] = @approve.errors.full_messages
                redirect_to @approve
            end
            
        end
        
    end
    

    
    
    
    private
  
    def submit_params
        params.require(:submission).permit(:title, :length, :link, :contact, :description, :reuse, :has_rights, :preferred_month, :password, :status, :reason, :winning_month, :winning_place, :best_of_month, :best_of_award)
        # params.permit(submission[:title, :length, :link, :contact, :description])
    end
    
    def require_login
        unless logged_in?
          flash[:error] = "You must be logged in to access this section"
          redirect_to login_url # halts request cycle
        end
    end
    
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/submissions/_form.html.erb
<div class="row submit-edit">
  <div class="col-md-8 col-md-offset-2">
    
    <%= form_for(@submission) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <% if current_user.admin? %>
        <div class="submit-edit--admin">
          <div class="row">
            <div class="submit-edit--title-bar">
                <h3 class="submit-edit--title">Admin Board</h3>
            </div>

            <div class="col-sm-3 ">
              <%= f.label :contact, "Contact Notes" %>
            </div>
            <div class="col-sm-9 submit-edit--input" >
              <%= f.text_field :contact, class: '', placeholder: "Any needed notes about person or submission" %>
            </div>

            <div class="col-sm-3 ">
              <%= f.label :status, "Status" %> 
            </div>
            <div class="col-sm-9">
              <%= f.select :status, ['Being Reviewed', 'February 2020','March 2020','April 2020','May 2020','Jun 2020','July 2020', 'August 2020','September 2020', 'November 2020', 'December 2020', 'Janruary 2021', 'February 2020', 'March 2021', 'April 2021', 'May 2021'], class: 'submit-edit--form-text' %>  
            </div>
              
            <div class="col-sm-3 ">
              <%= f.label :reason %>
            </div>
            <div class="col-sm-9">
              <%= f.text_field :reason, class: '' %>
            </div>
              
            <div class="col-sm-3 ">
              <%= f.label :contact, "Archived" %>
            </div>
            <div class="col-sm-9">
              <%= f.select :archive, ['true', 'false' ]  %>
            </div>
          
            <div class="col-sm-3  submit-edit--winner">
              <%= f.label :winning_month, "Winning Month" %>
            </div>
            <div class="col-sm-9">
              <%= f.select :winning_month, ['none','February 2020','March 2020','April 2020','May 2020','Jun 2020','July 2020','August 2020','September 2020', 'November 2020', 'December 2020', 'Janruary 2021', 'February 2020', 'March 2021', 'April 2021', 'May 2021'], class: '' %>
            </div>
          
            <div class="col-sm-3  submit-edit--winner">
              <%= f.label :winning_place, "Winning Place" %>
            </div>
            <div class="col-sm-9">
              <%= f.select :winning_place,['none','1st','2nd','3rd'], class: '' %>
            </div>
              
            <div class="col-sm-3  submit-edit--best">
              <%= f.label :best_of_month, "Best of Month" %>
            </div>
            <div class="col-sm-9">
              <%= f.select :best_of_month, ['none','March','September'], class: '', placeholder: "best way to get in touch" %>
            </div>

            <div class="col-sm-3  submit-edit--best">
              <%= f.label :best_of_award, "Best of Award" %>
            </div>
            <div class="col-sm-9">
              <%= f.text_field :best_of_award, class: '', placeholder: "best way to get in touch" %>
            </div>
          </div>
        </div>
   
      <%end%>
      
      <div class="row">
      <div class="col-sm-3 ">
        <%= f.label :title, "Title" %>
      </div>
      <div class="col-sm-9">
        <%= f.text_field :title, class: '' %>
      </div>
    
      <div class="col-sm-3 ">
        <%= f.label :length, "Runtime" %>
      </div>
      <div class="col-sm-9">
        <%= f.select :length, ['1','2','3','4','5','6', '7','8','9','10'] %>  
      </div>

      <div class="col-sm-3 ">
        <%= f.label :Link, 'Link' %>
      </div>
      <div class="col-sm-9">
        <%= f.text_field :link %>
      </div>

      <div class="col-sm-3 ">
        <%= f.label :password, 'Password' %>
      </div>
      <div class="col-sm-9">
        <%= f.text_field :password, class: '' %>
      </div>

      <div class="col-sm-3">
        <%= f.label :description, "Brief Synopsis" %>
      </div>
      <div class="col-sm-9 ">
        <%= f.text_area :description, class: '', rows: '4', placeholder: "Tell us about your film in to lines." %>
      </div>

      <div class="col-sm-4">
        <%= f.label :preferred_month, "Preferred Month" %>
      </div>
      <div class="col-sm-9">
        <%= f.select :preferred_month, ['Any Month', 'February 2020','March 2020','April 2020','May 2020','Jun 2020','July 2020', 'August 2020','September 2020', 'November 2020', 'December 2020', 'Janruary 2021', 'February 2020', 'March 2021', 'April 2021', 'May 2021'], class: '' %>  
      </div>
    </div>
    
    <div class="row">
      <div class="col-xs-2 text-right">
        <%= f.check_box :reuse %> 
      </div>
      <div class="col-xs-10">
        <%= f.label :reuse, "Allow Curious Comedy to replay film at other events.", class: 'text-left' %>
      </div>
        
    </div>
      
    <div class="row">
      <div class="col-xs-2 text-right">
          <%= f.check_box :has_rights, class: ''%> 
        </div>
        <div class="col-xs-10">
          <%= f.label :has_rights, "You have all necessary right to play this video at Curious Comedy Theater.", class: 'text-left' %>
        </div>
      </div>

      <div class="col-sm-4 text-center top-spacer-md">
        <%= link_to "Delete Submission", @submission, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-lg btn-danger top-bump' %>
      </div>
      <div class="col-sm-4 col-sm-offset-4 text-center top-spacer-md">
        <%= f.submit "Update", class: "btn btn-primary btn-lg" %>
      </div>
    </div> 
  </div>
  <% end %>
    

  </div>

app/views/submissions/_player.html.erb
<div class="player--title"> 
    <%= submission.title %> 
</div>
<div class="player--video">
    <div class="flex-video widescreen"><%= get_video_iframe(submission.link) %>  </div>   
</div>
<div class="player--place">
   <% if submission.winning_month %> <%= submission.winning_place %> in <%= submission.winning_month %> <%else %> Status: <%= submission.status %> <%end%>
</div>

app/views/submissions/_submission.html.erb
<div class="player">
<% if current_user.admin? %>
<div class='row player--buttons'>
    <div class='col-xs-7'>
        <%= link_to "Edit", edit_submission_path(submission), class: 'btn btn-info btn-block' %>
    </div>
    <div class="col-xs-5">
        <div class="dropdown">
            <button class="btn btn-success btn-block dropdown-toggle" type="button" data-toggle="dropdown"><%= submission.status %>
            <span class="caret"></span></button>
            <ul class="dropdown-menu">
                <li><%= link_to "February 2020", submission_path(:id => submission, :status => 'February 2020'), method: :status_change %></li>
                <li><%= link_to "March 2020", submission_path(:id => submission, :status => 'March 2020'), method: :status_change %></li>
                <li><%= link_to "April 2020", submission_path(:id => submission, :status => 'April 2020'), method: :status_change %></li>
                <li><%= link_to "March 2020", submission_path(:id => submission, :status => 'March 2020'), method: :status_change %></li>
                <li><%= link_to "April 2020", submission_path(:id => submission, :status => 'April 2020'), method: :status_change %></li>
                <li><%= link_to "May 2020", submission_path(:id => submission, :status => 'May 2020'), method: :status_change %></li>
                <li><%= link_to "June 2020", submission_path(:id => submission, :status => 'June 2020'), method: :status_change %></li>
                <li><%= link_to "July 2020", submission_path(:id => submission, :status => 'July 2020'), method: :status_change %></li>
                <li><%= link_to "August 2020", submission_path(:id => submission, :status => 'August 2020'), method: :status_change %></li>
                <li><%= link_to "September 2020", submission_path(:id => submission, :status => 'September 2020'), method: :status_change %></li>
                <li><%= link_to "November 2020", submission_path(:id => submission, :status => 'November 2020'), method: :status_change %></li>
                <li><%= link_to "December 2020", submission_path(:id => submission, :status => 'December 2020'), method: :status_change %></li>
                <li><%= link_to "January 2021", submission_path(:id => submission, :status => 'January 2021'), method: :status_change %></li>
                <li class="admin--reject"><%= link_to "Reject", submission_path(:id => submission, :status => 'reject'), method: :status_change %></li>
                <li class="admin--archive"><%= link_to "Archive", submission_path(:id => submission, :status => 'archive'), method: :status_change %></li>
                <li class="admin--review"><%= link_to "Being Reviewed", submission_path(:id => submission, :status => 'review'), method: :status_change %></li>
            </ul>
        </div> 
    </div>

</div>
<% end  %>
<div class="row player--clip">
    <div class="col-md-7"> <!--PLAYER Left Side | Video -->
        <div class="player--title"> 
        <%= link_to submission.title, submission %> 
        </div>

        <div class="player--video">
        <div class="flex-video add-pad widescreen"><%= get_video_iframe(submission.link) %> </div>   
        </div>

        <div class="player--place">
        <% if submission.winning_month %> <%= submission.winning_place %> in <%= submission.winning_month %> <%else %> Status: <%= submission.status %> <%end%>
        </div>
    </div> <!-- END Left side -->

    <div class="col-md-5 player--right"><!--Player Right Side | Details-->
        <div class="row">
            <!--STATUS-->
                <div class="col-xs-4 player--info-title player--info-status">
                    Status : 
                </div>
                <div class="col-xs-8 player--info-data player--info-status">
                    <%= submission.status %>
                </div>

            <!--POSTED BY-->
                <div class="col-xs-4 player--info-title">
                    Posted By :
                </div>
                <div class="col-xs-8 player--info-data">
                    <%= submission.user.name %>
                </div>
                
            <!-- EMAIL -->
                <div class="col-xs-4 player--info-title">
                    Email : 
                </div>
                <div class="col-xs-8 player--info-data">
                    <%= submission.user.email %>
                </div>
                
            <!--RUNTIME-->
                <div class="col-xs-4 player--info-title">
                    Runtime :
                </div>
                <div class="col-xs-8 player--info-data">
                    <%= submission.length %> Minutes
                </div>
                
            <!--PASSWORD-->
                <div class="col-xs-4 player--info-title">
                    password : 
                </div>
                <div class="col-xs-8 player--info-data">
                    <%= submission.password %> &nbsp;
                </div>
                
            <!--REPLAY-->
                <div class="col-xs-4 player--info-title">
                    Replay :    
                </div>
                <div class="col-xs-8 player--info-data">
                    <%= submission.reuse ? 'Yes' : 'No' %>
                </div>
                
            <!--PREFERRED MONTH-->
                <div class="col-xs-4 player--info-title">
                    Month :
                </div>
                <div class="col-xs-8 player--info-data">
                    <%= submission.preferred_month %>
                </div>
                        
            <!--SUBMIT DATE-->
                <div class="col-xs-4 player--info-title">
                    Submitted:
                </div>
                <div class="col-xs-8 player--info-data">
                    <%= time_ago_in_words(submission.created_at) %> Ago.
                </div>

    </div> <!-- END Row -->
    
    <!--STATE-->
    <div class = 'row'>
        <% if submission.status != 'Being Reviewed' %>
            <div class="col-xs-4 player--info-title">
                Playing:
            </div>
            <div class="col-xs-8 player--info-data">
                <%= submission.status %>  
            </div>
        <%end%>
        
        <% if submission.winning_month %>
            <div class="col-xs-4 player--info-title">
                Placed:
            </div>
            <div class="col-xs-8 player--info-data">
                <%= submission.winning_place %>  in  <%= submission.winning_month %> 
            </div>
        <%end%>
        
        <% if submission.best_of_month %>
            <div class="col-xs-4 player--info-title">
                Best of:
            </div>
            <div class="col-xs-8 player--info-data">
                <%= submission.best_of_award  %> award for  <%= submission.best_of_month %> 
            </div>
        <%end%>
        </div>
        <div class='row'>
            <div class="col-md-12 player--info-description-title">
                <span class="player--details-title"> Description </span> 
            </div>
            <div class="col-md-12 player--info-description-full">
                <span class="player--details"> <%= submission.description %> </span>
            </div>
        </div>
    </div><!-- END Right side-->
</div><!-- END row-->


</div>
  

app/views/submissions/approved_index.html.erb
<div class="row top-spacer-md">
    <div class="col-md-8">
        <h2 class= "text-center">Approved : <%= @approval.count %></h2>
    </div>
    <div class="col-md-4">
        <h3 class= "text-center">Total Time : <%= @runtime %> Minutes</h3>
    </div>
</div>
<div class="row">
    <%= render '/shared/approved_list_out' %>    
</div>

app/views/submissions/approved_month.html.erb
<div class="row top-spacer-lg">
  <div class="col-md-8">
    <h2 class= "text-center"><%= @month %> Submissions: <%= @approval.count %></h2>
  </div>
  <div class="col-md-4">
    <h3 class= "text-center">Total Time : <%= @runtime %> Minutes</h3>
  </div>
</div>

<div class="row">
  <%= render '/shared/approved_list_out' %>    
</div>

app/views/submissions/archive.html.erb
<div class="row">
       
    <div class="col-md-8">
        <h2 class= "text-center"> Archived Submissions  <%= @approval.count %></h2>
    </div>
    <div class="col-md-4">
        <h3 class= "text-center">Total Time : <%= @runtime %> Minutes</h3>
    </div>
</div>
<div class="row">
    <%= render '/shared/approved_list_out' %>    
</div>

app/views/submissions/edit.html.erb
<div class="row text-center top-spacer-md">
    <h1 class="box">Edit | <%= @submission.title %> </h1>
</div>
 
<%= render 'form' %> 

 

app/views/submissions/get_all.html.erb
<% if current_user.admin? %>
<div class="row">
  <h2 class= "text-center"> All Submissions : <%= @submissions.count %></h2> 
</div>

<div class="row">
  <%= will_paginate @submissions, class: "text-center" %>  
</div>

<div class="row">
 
    <% @submissions.each do |submission| %>
      
        <%= render submission %>
    
    <% end %>

</div>

<div class="row">
  <%= will_paginate @submissions, class: "text-center" %>
</div>

<% else %>
  <h3 class="text-center">You do not have permission to view this page</h3>
<% end %>

app/views/submissions/index.html.erb
<% if current_user.admin? %>
<div class="row">
  <h2 class= "text-center">Submissions : <%= @submissions.count %></h2> 
</div>

<div class="row">
  <%= will_paginate @submissions, class: "text-center" %>  
</div>

<div class="row">
 
    <% @submissions.each do |submission| %>
      
        <%= render submission %>
    
    <% end %>

</div>

<div class="row">
  <%= will_paginate @submissions, class: "text-center" %>
</div>

<% else %>
  <h3 class="text-center">You do not have permission to view this page</h3>
<% end %>

app/views/submissions/new.html.erb
<div class="col-md-8 col-md-offset-2">
    <% if logged_in? %>
       <%= render '/shared/submit_form' %>
    <%else%>
      <%= render '/shared/please_log_in' %>
    <%end%>
</div>

app/views/submissions/show.html.erb
<div class="well <% if @submission.status == "Rejected" %> reject 
                <% elsif @submission.status =="Being Reviewed" %> review
                <% else %> approved
                <%end%>"> 
    <div class="row"> <!--TITLE START-->
      <div class="col-md-7 text-center">
          <h3><%= @submission.title %></h3> 
      </div>  
      <div class="col-md-5 text-center">
          <h3>Status : <%= @submission.status %></h3>
      </div>
    </div><!--TITLE END-->
    
    
    <div class="row"><!--CONTENT START -->
    
        <div class="col-md-7"><!-- Video Player Start-->
            <div class="flex-video widescreen"><%= get_video_iframe(@submission.link) %> </div>
        </div> <!-- Video Player End -->
        
        <div class="col-md-5"><!-- Video Details Start-->
            <!--USER NAME-->
            <div class="row">
                <div class="col-xs-4 text-right simple-label">
                    User :
                </div>
                 <div class="col-xs-8 text-left simple-label">
                     <%= link_to @user.name, @user %> 
                 </div> 
            </div>
            
            <% if current_user.admin? %>
            <!--EMAIL-->
            <div class="row">
                <div class="col-xs-4 text-right simple-label">
                    Email :
                </div>
                 <div class="col-xs-8 text-left simple-label">
                     <%= mail_to @user.email %> 
                 </div> 
            </div>                
            <%end%>
            
            <!--RUN TIME-->
            <div class="row">
                <div class="col-xs-4 text-right simple-label">
                    length : 
                </div>
                <div class="col-xs-8 text-left simple-label">
                    <%= @submission.length %> Minutes
                </div>
            </div>
            
            <!--LINK-->
            <div class="row">
                <div class="col-xs-4 text-right simple-label">
                    Link : 
                </div>
                <div class="col-xs-8 text-left simple-label">
                    <a href= "<%= @submission.link %>" target = "blank"><%= @submission.title %> </a>  
                </div>
            </div>
            
            <% if current_user.admin? %>
            <!--LINK-->
            <div class="row">
                <div class="col-xs-4 text-right simple-label">
                    Password: 
                </div>
                <div class="col-xs-8 text-left simple-label">
                    <%= @submission.password %> 
                </div>
            </div>            
            <%end%>
            
            
            <!--Re-Play True-->
            <div class="row">
                <div class="col-xs-4 text-right simple-label">
                    Re-Play :  
                </div>
                <div class="col-xs-8 text-left simple-label">
                    <%= @submission.reuse %>
                </div>
            </div>
            
            <!-- Preferred Month -->
            <div class="row">
                <div class="col-xs-4 text-right simple-label">
                    Preferred :  
                </div>
                <div class="col-xs-8 text-left simple-label">
                  <%= @submission.preferred_month %>
                </div>
            </div>
            
            <!-- Status -->
        
            <div class="row">
                <div class="col-xs-4 text-right simple-label">
                    Status :  
                </div>
                <div class="col-xs-8 text-left simple-label">
                    <%= @submission.status %>
                </div>
            </div>
            
            <% if @submission.status == 'Rejected'%>
                <div class="row">
                    <div class="col-xs-4 text-right simple-label">
                        reason :  
                    </div>
                    <div class="col-xs-8 text-left simple-label">
                        <%= @submission.reason %>
                    </div>
                </div>
            <% end %>

            <hr>
        <div class="row">
             <!-- Edit -->
                <div class="top-bump">
                    <%= link_to "EDIT", edit_submission_path, class: "btn btn-info btn-block" %>   
                </div>
        </div>
            <% if current_user.admin? %>
                <div class="row"> <!-- BUTTONS START-->
                    
                    
                        <!-- Change Status -->
                            <div class="top-bump">
                                <div class="dropdown">
                                    <button class="btn btn-success btn-block dropdown-toggle" type="button" data-toggle="dropdown"><%= @submission.status %>
                                      <span class="caret"></span></button>
                                      <ul class="dropdown-menu">
                                        <li><%= link_to "01 October", submission_path(:status => 'oct'), method: :status_change %></li>
                                        <li><%= link_to "02 November", submission_path(:status => 'nov'), method: :status_change %></li>
                                        <li><%= link_to "03 December", submission_path(:status => 'dec'), method: :status_change %></li>
                                        <li><%= link_to "04 January", submission_path(:status => 'jan'), method: :status_change %></li>
                                        <li><%= link_to "05 February", submission_path(:status => 'feb'), method: :status_change %></li>
                                        <li><%= link_to "06 March", submission_path(:status => 'mar'), method: :status_change %></li>
                                        <li><%= link_to "07 April", submission_path(:status => 'apr'), method: :status_change %></li>
                                        <li><%= link_to "08 May", submission_path(:status => 'may'), method: :status_change %></li>
                                        <li><%= link_to "09 June", submission_path(:status => 'jun'), method: :status_change %></li>
                                        <li><%= link_to "10 July", submission_path(:status => 'jul'), method: :status_change %></li>
                                        <li><%= link_to "11 August", submission_path(:status => 'aug'), method: :status_change %></li>
                                        <li><%= link_to "12 September", submission_path(:status => 'sep'), method: :status_change %></li>
                                        <li><%= link_to "Reject", submission_path(:status => 'reject'), method: :status_change %></li>
                                        <li><%= link_to "Archive", submission_path(:status => 'archive'), method: :status_change %></li>
                                        <li><%= link_to "Being Reviewed", submission_path(:status => 'review'), method: :status_change %></li>
                                      </ul>
                                </div> 
                            </div>
                   
                </div>
            <% end  %>
        </div><!-- Video Details End-->
        
        </div>
        <div class="row ">
            <div class="col-xs-12 text-left bottom-border ">
               <h4> Description : </h4>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12 text-left box top-bump">
              <p>  <%= @submission.description %> </p>
            </div>
        </div>
        
        
    </div><!--END WELL-->
    